/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/templates/**/*.html",
    "./app/static/js/**/*.js"
  ],
  safelist: [
    'animate-fade-in',
    'animate-fade-in-fast',
    'animate-fade-in-slow',
    'animate-fade-in-up',
    'animate-fade-in-up-fast',
    'animate-fade-in-down',
    'animate-slide-in-left',
    'animate-slide-in-right',
    'animate-scale-in',
    'animate-bounce-in',
    'animate-pulse-soft',
    'animate-wiggle',
    'animate-spin-slow',
    'animate-float',
    'animate-slide-up',
    'animate-slide-down',
    'hover-elevate',
    'stagger-children',
  ],
  theme: {
    extend: {
      colors: {
        // Project color tokens (from original style.css)
        bg: '#F9FAFB',
        card: '#FFFFFF',
        accent: '#2563EB',
        destructive: '#DC2626',
        success: '#059669',
        text: '#1F2937',
        border: '#D1D5DB',
        'text-muted': '#6B7280',
        'text-dark': '#1F2937',
        'gray-50': '#F9FAFB',
        'gray-100': '#F3F4F6',
        'gray-200': '#E5E7EB',
        'gray-300': '#D1D5DB',
        'gray-400': '#9CA3AF',
        'gray-500': '#6B7280',
        'gray-700': '#374151',
        'gray-800': '#1F2937',
        'blue-dark': '#1D4ED8',
        'red-dark': '#B91C1C',
        'amber-600': '#D97706',
        'amber-700': '#B45309',
        'green-700': '#047857',
        'emerald-300': '#A7F3D0',
        'amber-200': '#FDE68A',
        'amber-300': '#FCD34D',
        'indigo-100': '#DBEAFE',
        'indigo-200': '#BFDBFE',
        'purple-100': '#F5F3FF',
        'purple-200': '#DDD6FE',
        'purple-700': '#6D28D9',
        'yellow-100': '#FFFBEB',
        'yellow-200': '#FEF3C7',
        'rose-50': '#FEF2F2',
        'rose-100': '#FFE4E4',
      },
      fontFamily: {
        sans: ['"Noto Sans VN"', 'Roboto', 'system-ui', '-apple-system', 'sans-serif'],
      },
      fontSize: {
        xs: ['12px', { lineHeight: '1.5rem' }],
        sm: ['14px', { lineHeight: '1.5rem' }],
        base: ['16px', { lineHeight: '1.5rem' }],
        lg: ['18px', { lineHeight: '1.5rem' }],
        xl: ['20px', { lineHeight: '1.2' }],
        '2xl': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
        '3xl': ['32px', { lineHeight: '1.1', fontWeight: '600' }],
      },
      spacing: {
        '4': '4px',
        '8': '8px',
        '12': '12px',
        '16': '16px',
        '20': '20px',
        '24': '24px',
        '32': '32px',
        '40': '40px',
        '44': '44px',
        '48': '48px',
        '56': '56px',
        '64': '64px',
        '72': '72px',
        '80': '80px',
        '96': '96px',
      },
      borderRadius: {
        sm: '4px',
        md: '8px',
        lg: '12px',
        full: '9999px',
      },
      boxShadow: {
        sm: '0 1px 3px rgba(0, 0, 0, 0.1)',
        md: '0 2px 8px rgba(0,0,0,0.08)',
        lg: '0 4px 12px rgba(0,0,0,0.08)',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in-down': {
          '0%': { opacity: '0', transform: 'translateY(-12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-in-left': {
          '0%': { opacity: '0', transform: 'translateX(-12px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'slide-in-right': {
          '0%': { opacity: '0', transform: 'translateX(12px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'bounce-in': {
          '0%': { opacity: '0', transform: 'scale(0.3)' },
          '50%': { opacity: '1', transform: 'scale(1.05)' },
          '75%': { transform: 'scale(0.95)' },
          '100%': { transform: 'scale(1)' },
        },
        'pulse-soft': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
        'wiggle': {
          '0%, 100%': { transform: 'rotate(-3deg)' },
          '50%': { transform: 'rotate(3deg)' },
        },
        'spin-slow': {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-4px)' },
        },
        'slide-up': {
          '0%': { transform: 'translateY(0)' },
          '100%': { transform: 'translateY(-100%)' },
        },
        'slide-down': {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(0)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.2s ease-out',
        'fade-in-fast': 'fade-in 0.15s ease-out',
        'fade-in-slow': 'fade-in 0.4s ease-out',
        'fade-in-up': 'fade-in-up 0.3s ease-out',
        'fade-in-up-fast': 'fade-in-up 0.2s ease-out',
        'fade-in-down': 'fade-in-down 0.3s ease-out',
        'slide-in-left': 'slide-in-left 0.2s ease-out',
        'slide-in-right': 'slide-in-right 0.2s ease-out',
        'scale-in': 'scale-in 0.2s ease-out',
        'bounce-in': 'bounce-in 0.5s ease-out',
        'pulse-soft': 'pulse-soft 2s ease-in-out infinite',
        'wiggle': 'wiggle 1s ease-in-out infinite',
        'spin-slow': 'spin-slow 3s linear infinite',
        'float': 'float 2s ease-in-out infinite',
        'slide-up': 'slide-up 0.2s ease-out',
        'slide-down': 'slide-down 0.2s ease-out',
      },
      transitionDelay: {
        75: '75ms',
        100: '100ms',
        150: '150ms',
        200: '200ms',
        300: '300ms',
        500: '500ms',
        700: '700ms',
        1000: '1000ms',
      },
    },
  },
  plugins: [
    require('@tailwindcss/line-clamp'),
    // Custom component styles for buttons
    function({ addComponents }) {
      addComponents({
        '.btn': {
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          height: '44px',
          padding: '0 24px',
          borderRadius: '8px',
          border: 'none',
          fontSize: '14px',
          fontWeight: '600',
          fontFamily: 'inherit',
          lineHeight: '1',
          cursor: 'pointer',
          textDecoration: 'none',
          '&:hover': { textDecoration: 'none' },
          '&:focus-visible': { outline: '2px solid #2563EB', outlineOffset: '2px' },
          '&:disabled, &[disabled]': { cursor: 'not-allowed' },
        },
        '.btn-primary': {
          backgroundColor: '#2563EB',
          color: '#fff',
          '&:hover': { backgroundColor: '#1D4ED8' },
          '&:disabled, &[disabled]': { backgroundColor: '#93C5FD' },
        },
        '.btn-secondary': {
          backgroundColor: '#fff',
          border: '1px solid #D1D5DB',
          color: '#1F2937',
          '&:hover': { backgroundColor: '#F9FAFB' },
        },
        '.btn-danger': {
          backgroundColor: '#DC2626',
          color: '#fff',
          '&:hover': { backgroundColor: '#B91C1C' },
          '&:disabled, &[disabled]': { backgroundColor: '#FCA5A5' },
        },
        '.btn-link': {
          backgroundColor: 'transparent',
          border: 'none',
          padding: '0',
          fontSize: '14px',
          fontWeight: '600',
          cursor: 'pointer',
        },
      })
    }
  ],
}
